name: PR summary
author: Karthikeyan
description: Generating explanation of PR which has been opened by the developer.
inputs:
  OPENAI_API_KEY:
    description: Open AI API key
    required: true
  GITHUB_TOKEN:
    description: Github Token
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
